version: '3.8'

services:
  app:
    build: .
    image: cblpay_app:latest
    container_name: cblpay_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    depends_on:
      - db

  web:
    image: nginx:alpine
    container_name: cblpay_web
    restart: unless-stopped
    ports:
      - "8128:80"
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: cblpay_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: cbl_pay
      MYSQL_USER: cbl
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cblpay_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "8181:80"
    depends_on:
      - db

volumes:
  db_data:
